### ISSUE TITLE
Upgrade package versions in the **package.json** file please.

### ISSUE THREAD

**Issue by otabekoff** [biigpongsatorn/vue-component-generator#2]
Now, I tried to install and it is successful but after 12minutes 28seconds.
This is because the old modules. Then I tried to create mext project and didn't run yarn command.
Just run yarn upgrade and it got lesser than 2 minutes. I know yarn is somehow faster than NPM.
And I can say you should upgrade modules on some periods of time.

**Comment by biigpongsatorn** [comment]
This template is work as well on Vue CLI version 2 and it does not support version 3 yet.

**Comment by otabekoff** [comment]
Thank you very much for the response. And yes I wanted to see this project with VueJS 3 and a good composition API usage. But I see some warnings while the installation. IS this because of VueJS 3? Ok I am closing this issue now. And whatever, I wait for the new release of this project for VueJS 3 with a nice example. Let me know if it will be released OK? Thank you for such a good starter project.
